export const GAMES_LIST = 'GAMES_LIST'
export const SELECT_GAME = 'SELECT_GAME'
export const SELECT_GAME_MODE = 'SELECT_GAME_MODE'
export const SELECT_GAME_DIFFICULT = 'SELECT_GAME_DIFFICULT'

//export const CHECK_SESSION = 'CHECK_SESSION'
//export const CHECK_SUBMIT_LOGIN_FORM = 'CHECK_SUBMIT_LOGIN_FORM'
//export const LOGIN = 'LOGIN'
//export const LOGOUT = 'LOGOUT'