//games
export const GAMES_LIST = 'GAMES_LIST'
//app memory game
export const SELECT_GAME = 'SELECT_GAME'
export const SELECT_GAME_MODE = 'SELECT_GAME_MODE'
export const SELECT_GAME_DIFFICULT = 'SELECT_GAME_DIFFICULT'
export const GAME_INIT = 'GAME_INIT'
export const GAME_PAUSE = 'GAME_PAUSE'
export const GAME_RESUME = 'GAME_RESUME'
export const GAME_WIN = 'GAME_WIN'
export const GAME_LOSE = 'GAME_LOSE'
export const GAME_EXIT = 'GAME_EXIT'
//board
export const RESET_BOARD = 'RESET_BOARD'
export const BOARD_READY = 'BOARD_READY'
export const CLICK_SQUARE = 'CLICK_SQUARE'
export const SQUARES_FOUNDED = 'SQUARES_FOUNDED'
export const ALL_SQUARES_FOUNDED = 'ALL_SQUARES_FOUNDED'
export const SQUARES_SHUFFLE = 'SQUARES_SHUFFLE'
export const SQUARES_SHUFFLE_END = 'SQUARES_SHUFFLE_END'
//timer
export const START_TIMER = 'START_TIMER'
export const DECREMENT_TIMER = 'DECREMENT_TIMER'
export const INCREMENT_TIMER = 'INCREMENT_TIMER'
export const TIME_UP = 'TIME_UP'
export const STOP_TIMER = 'STOP_TIMER'
export const RESTART_TIMER = 'RESTART_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
//session user
export const CHECK_SESSION = 'CHECK_SESSION'
export const CHECK_LOGIN_FORM = 'CHECK_LOGIN_FORM'
export const LOGIN = 'LOGIN'
//export const LOGOUT = 'LOGOUT'